version: '3'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    image: angular:latest
    container_name: angular
    tty: true
    volumes:
    - ./notes:/notes/
    ports:
    - 4200:4200

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
